tls:
  options:
    default:
      minVersion: VersionTLS13

http:
  middlewares:
    hsts:
      headers:
        stsseconds: 63072000
        stsIncludeSubdomains: true
    compression:
      compress: {}
    evcc-basic:
      basicAuth:
        users:
          - "garmin:{{env "GARMIN_BASIC_PW"}}"
  routers:
    evcc:
      entryPoints:
        - http
      service: evcc
      rule: Host(`evcc.{{env "DOMAINNAME"}}`)
    espressoapi:
      entryPoints:
        - http
      service: espressoapi
      rule: Host(`espresso.{{env "DOMAINNAME"}}`) && PathPrefix(`/api`)
    evcc-basic:
      entryPoints:
        - http
      service: evcc-basic
      rule: Host(`evcc-basic.{{env "DOMAINNAME"}}`)
      middlewares:
        - evcc-basic
  services:
    espressoapi:
      loadBalancer:
        servers:
          - url: "http://pi.fritz.box:8000/"
    evcc:
      loadBalancer:
        servers:
          - url: "http://zaehler.fritz.box:7070/"
    evcc-basic:
      loadBalancer:
        servers:
          - url: "http://zaehler.fritz.box:7070/"
