tls:
  options:
    default:
      minVersion: VersionTLS13

http:
  middlewares:
    hsts:
      headers:
        stsseconds: 63072000
        stsIncludeSubdomains: true
  routers:
    evcc:
      entryPoints:
        - http
      service: evcc
      rule: Host(`evcc.{{env "DOMAINNAME"}}`)
    espressoapi:
      entryPoints:
        - http
      service: espressoapi
      rule: Host(`espresso.{{env "DOMAINNAME"}}`) && PathPrefix(`/api`)
  services:
    espressoapi:
      loadBalancer:
        servers:
          - url: "http://pi.fritz.box:8000/"
    evcc:
      loadBalancer:
        servers:
          - url: "http://zaehler.fritz.box:7070/"
